name: "Configuration Editor"
version: "1.0.21"
slug: "conf-edit-ha"
description: "Lightweight YAML editor with syntax highlighting and entity autocomplete"
url: "https://github.com/roman-pinchuk/conf-edit-ha"
image: "ghcr.io/roman-pinchuk/conf-edit-ha-{arch}"
arch:
  - aarch64
  - amd64
init: false
startup: services
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web interface"
ingress: true
panel_icon: mdi:file-document-edit
panel_title: "Config Editor"
hassio_api: true
hassio_role: manager
homeassistant_api: true
auth_api: true
map:
  - homeassistant_config:rw
  - ssl:ro
  - addons:ro
  - backup:ro
options:
  theme: "auto"
schema:
  theme: list(auto|light|dark)
